
"use client";

import { useState, useEffect, useRef } from "react";
import type { Photo } from "@/lib/types";
import { PageContainer } from "@/components/page-container";
import Image from "next/image";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { PlusCircle, Loader2, Trash2 } from "lucide-react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger, DialogFooter, DialogClose } from "@/components/ui/dialog";
import { useToast } from "@/hooks/use-toast";
import DecorativeBorder from "@/components/decorative-border";
import { Card } from "@/components/ui/card";
import { supabase } from "@/lib/supabaseClient";

export default function GalleryPage() {
  const [photos, setPhotos] = useState<Photo[]>([]);
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [selectedFiles, setSelectedFiles] = useState<File[]>([]);
  const [newPhotoCaption, setNewPhotoCaption] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [isClient, setIsClient] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const { toast } = useToast();

  useEffect(() => {
    setIsClient(true);
    fetchPhotos();
  }, []);

  const fetchPhotos = async () => {
    setIsLoading(true);
    try {
      const { data, error } = await supabase
        .from("gallery_photos")
        .select("*")
        .order("date_added", { ascending: false });

      if (error) {
        throw error;
      }
      if (data) {
        setPhotos(data as Photo[]);
      }
    } catch (error: any) {
      console.error("Error fetching photos from Supabase:", error);
      toast({
        title: "Error Fetching Photos",
        description: error.message || "Could not load photos from the database.",
        variant: "destructive",
      });
      setPhotos([]); // Set to empty array on error
    } finally {
      setIsLoading(false);
    }
  };


  const handleFileChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    if (event.target.files) {
      setSelectedFiles(Array.from(event.target.files));
    } else {
      setSelectedFiles([]);
    }
  };

  const handleAddPhoto = async () => {
    if (selectedFiles.length === 0) {
      toast({ title: "Error", description: "Please select image file(s).", variant: "destructive" });
      return;
    }
    setIsLoading(true);

    const newPhotosPromises = selectedFiles.map(file => {
      return new Promise<{ url: string; caption: string; "data-ai-hint": string } | null>((resolve) => {
        const reader = new FileReader();
        reader.onloadend = () => {
          resolve({
            url: reader.result as string,
            caption: newPhotoCaption, // Apply common caption
            "data-ai-hint": "uploaded image" // Common AI hint
          });
        };
        reader.onerror = () => {
          toast({ title: "Error Reading File", description: `Failed to read ${file.name}.`, variant: "destructive" });
          resolve(null);
        };
        reader.readAsDataURL(file);
      });
    });

    try {
      const results = await Promise.all(newPhotosPromises);
      const successfullyReadPhotoData = results.filter(data => data !== null) as { url: string; caption: string; "data-ai-hint": string }[];

      if (successfullyReadPhotoData.length === 0 && selectedFiles.length > 0) {
        toast({ title: "No Photos Processed", description: "Could not process any of the selected files.", variant: "default" });
        setIsLoading(false);
        return;
      }

      if (successfullyReadPhotoData.length > 0) {
        const photosToInsert = successfullyReadPhotoData.map(pData => ({
          url: pData.url,
          caption: pData.caption,
          data_ai_hint: pData["data-ai-hint"],
          // id and date_added will be generated by Supabase
        }));

        const { data: insertedPhotos, error } = await supabase
          .from("gallery_photos")
          .insert(photosToInsert)
          .select();

        if (error) {
          throw error;
        }

        if (insertedPhotos) {
          setPhotos(prevPhotos => [...(insertedPhotos as Photo[]), ...prevPhotos].sort((a,b) => new Date(b.date_added).getTime() - new Date(a.date_added).getTime()));
          toast({ title: "Success", description: `${insertedPhotos.length} photo(s) added to gallery and saved to database!` });
          setIsDialogOpen(false);
        }
      }
    } catch (error: any) {
      console.error("Error adding photos to Supabase:", error);
      toast({
        title: "Database Error",
        description: error.message || "Could not save photos to the database.",
        variant: "destructive",
      });
    } finally {
      setIsLoading(false);
      setSelectedFiles([]);
      setNewPhotoCaption("");
      if (fileInputRef.current) {
        fileInputRef.current.value = "";
      }
    }
  };

  const handleDeletePhoto = async (id: string) => {
    if (confirm("Are you sure you want to delete this photo from the database?")) {
      setIsLoading(true);
      try {
        const { error } = await supabase
          .from("gallery_photos")
          .delete()
          .match({ id: id });

        if (error) {
          throw error;
        }

        setPhotos(prevPhotos => prevPhotos.filter(p => p.id !== id));
        toast({ title: "Success", description: "Photo removed from gallery and database." });
      } catch (error: any) {
        console.error("Error deleting photo from Supabase:", error);
        toast({
          title: "Database Error",
          description: error.message || "Could not delete photo from the database.",
          variant: "destructive",
        });
      } finally {
        setIsLoading(false);
      }
    }
  };


  return (
    <PageContainer title="Our Photo Gallery">
      <Dialog open={isDialogOpen} onOpenChange={(isOpen) => {
        setIsDialogOpen(isOpen);
        if (!isOpen) {
          setSelectedFiles([]);
          setNewPhotoCaption("");
          if (fileInputRef.current) {
            fileInputRef.current.value = "";
          }
        }
      }}>
        <DialogTrigger asChild>
          <Button className="mb-6 bg-primary hover:bg-primary/90 text-primary-foreground font-body">
            {isClient && <PlusCircle className="mr-2 h-5 w-5" />}
            Add New Photo(s)
          </Button>
        </DialogTrigger>
        <DialogContent className="sm:max-w-[425px] bg-card border-primary/30">
          <DialogHeader>
            <DialogTitle className="font-headline text-2xl text-primary">Add Photo(s) to Gallery</DialogTitle>
          </DialogHeader>
          <div className="grid gap-4 py-4 font-body">
            <div className="space-y-1">
              <Label htmlFor="photoFile" className="text-foreground/80">Photo File(s)</Label>
              <Input id="photoFile" type="file" accept="image/*" onChange={handleFileChange} ref={fileInputRef} multiple />
            </div>
            <div className="space-y-1">
              <Label htmlFor="caption" className="text-foreground/80">Caption (Optional, applies to all)</Label>
              <Input id="caption" value={newPhotoCaption} onChange={(e) => setNewPhotoCaption(e.target.value)} />
            </div>
            {selectedFiles.length > 0 && (
              <div className="text-sm text-muted-foreground space-y-1">
                <p>{selectedFiles.length} file(s) selected:</p>
                {selectedFiles.length === 1 && selectedFiles[0] && (
                  <>
                    <p className="truncate ml-2">- {selectedFiles[0].name}</p>
                    <Image src={URL.createObjectURL(selectedFiles[0])} alt="Preview" width={100} height={100} className="mt-2 rounded-md aspect-square object-cover" />
                  </>
                )}
                {selectedFiles.length > 1 && (
                  <ul className="list-disc pl-6 max-h-24 overflow-y-auto text-xs">
                    {selectedFiles.slice(0, 5).map(file => <li key={file.name} className="truncate">{file.name}</li>)}
                    {selectedFiles.length > 5 && <li>...and {selectedFiles.length - 5} more.</li>}
                  </ul>
                )}
              </div>
            )}
          </div>
          <DialogFooter>
            <DialogClose asChild>
              <Button variant="outline" className="font-body border-primary text-primary hover:bg-primary/10" disabled={isLoading}>Cancel</Button>
            </DialogClose>
            <Button onClick={handleAddPhoto} className="bg-primary hover:bg-primary/90 text-primary-foreground font-body" disabled={isLoading || selectedFiles.length === 0}>
              {isLoading ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : null}
              Add Photo(s)
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {isLoading && photos.length === 0 && (
        <div className="flex justify-center items-center h-40">
            <Loader2 className="h-12 w-12 animate-spin text-primary" />
        </div>
      )}

      {!isLoading && photos.length === 0 ? (
         <DecorativeBorder className="text-center">
            <p className="font-body text-lg text-foreground/70 p-8">Your gallery is empty. Add some photos to start your visual journey!</p>
        </DecorativeBorder>
      ) : (
      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
        {photos.map((photo) => (
          <Card key={photo.id} className="group relative overflow-hidden rounded-lg shadow-lg border border-primary/10 aspect-square transform transition-all duration-300 hover:scale-105 hover:shadow-2xl hover:border-accent">
            <Image
              src={photo.url}
              alt={photo.caption || "Gallery image"}
              fill
              sizes="(max-width: 640px) 100vw, (max-width: 768px) 50vw, (max-width: 1024px) 33vw, 25vw"
              style={{ objectFit: "cover" }}
              className="transition-transform duration-500 group-hover:scale-110"
              data-ai-hint={photo['data_ai_hint'] || "gallery image"}
              unoptimized={photo.url.startsWith('data:image')}
            />
            {photo.caption && (
              <div className="absolute inset-x-0 bottom-0 bg-black/50 p-2 text-center">
                <p className="text-sm text-white font-body truncate">{photo.caption}</p>
              </div>
            )}
            <Button
              variant="destructive"
              size="icon"
              className="absolute top-2 right-2 opacity-0 group-hover:opacity-100 transition-opacity z-10 h-8 w-8"
              onClick={() => handleDeletePhoto(photo.id)}
            >
              {isClient && <Trash2 className="h-4 w-4" />}
            </Button>
          </Card>
        ))}
      </div>
      )}
    </PageContainer>
  );
}

    